spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MonSupplier
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: amina.el.hakik2@gmail.com
    password: meeb lrus wsxb nznh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true